Enhance Jenkins pipeline with Docker stages
Added stages for building, testing, and deploying a Docker image.

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,22 +1,57 @@
 pipeline {
     agent any
-    
+
+    environment {
+        DOCKER_IMAGE = "yourdockerhubusername/demo-jenkins-app"          #replace ur docker hub detail
+    }
+
     stages {
-        stage('Build') {
+        
+        stage('Clone Repo') {
             steps {
-                echo 'Building automatically'
-                echo 'welcome to Bhutan'              
+                sh 'git clone https://github.com/Mudassir-dev0ps/docker-deplo.git'     #replace ur GitHub repo
             }
         }
- stage('Test') {
+
+        stage('Install Dependencies & Test') {
             steps {
-                echo 'Testing automatically.'
+                sh 'pip install flask pytest'
+                
             }
         }
- stage('Deploy') {
+
+        stage('Build Docker Image') {
             steps {
-                echo 'Deploying automatically.'
+                sh 'docker build -t $DOCKER_IMAGE:${BUILD_NUMBER} .'
+            }
+        }
+
+        stage('Push to Docker Hub') {
+            steps {
+                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
+                    sh "echo $PASS | docker login -u $USER --password-stdin"
+                    sh "docker push $DOCKER_IMAGE:${BUILD_NUMBER}"
+                }
+            }
+        }
+
+        stage('Deploy to Docker') {
+            steps {
+                sh "docker rm -f demo-app || true"
+                sh "docker run -d -p 5000:5000 --name demo-app $DOCKER_IMAGE:${BUILD_NUMBER}"
             }
         }
     }
+
+    post {
+        success {
+            echo "Pipeline completed successfully!"
+        }
+        failure {
+            echo "Pipeline failed!"
+        }
+    }
 }
+
+
+
